### ISSUE TITLE
Create map markers, colors for different types of Places

### ISSUE THREAD

**Issue by woodb** [myfossil/myfossil-theme#137]
While implementing #86, we need colors and map marker icon for the following groups:

- Organization
- Interest Group
- Society
- Club
- City Park
- Collecting Site
- Museum
- National Park
- State Park
- Other

**Comment by woodb** [comment]
Quick note, I would only expect that the map marker is a color (no letter, no symbol)... here's a peak on how it's implemented currently:

![image](https://cloud.githubusercontent.com/assets/1631487/5843034/89b2bdde-a177-11e4-92ce-f86418816932.png)

**Comment by woodb** [comment]
Moved back to Milestone v0.4.0

**Comment by antonlegoo** [comment]
I had originally wanted to use SVG to make the setting of the colors flexible. However, I wanted to keep the styles declared in the theme SASS, which required external CSS for the SVG's which turned out to be more complicated than I had originally thought.

So for time's sake I ended up just creating PNGs. Below are the colors and corresponding filenames for each:

* Organization
 * Color: #b32121
 * File: /static/img/map/marker-Organization.png

* Interest Group
 * Color: #2121b3
 * File: /static/img/map/marker-Interest-Group.png

* Society
 * Color: #6a21b3
 * File: /static/img/map/marker-Society.png

* Club
 * Color: #00bfbf
 * File: /static/img/map/marker-Club.png

* City Park
 * Color: #b3b321
 * File: /static/img/map/marker-City-Park.png

* Collecting Site
 * Color: #b36a21
 * File: /static/img/map/marker-Collecting-Site.png

* Museum
 * Color: #216ab3
 * File: /static/img/map/marker-Museum.png

* National Park
 * Color: #1e611e
 * File: /static/img/map/marker-National-Park.png

* State Park
 * Color: #6ab321
 * File: /static/img/map/marker-State-Park.png

* Other
 * Color: #333333
 * File: /static/img/map/marker-Other.png
