### ISSUE TITLE
Activity feed displays too many text-inputs

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#181]
Each item in the activity feed is followed by an image of the currently logged in user, a text input field, and a "Post" button.  All content that appears below an activity item should not be visible until the user clicks the "Comment" link for the activity item.

![image](https://cloud.githubusercontent.com/assets/643301/9206575/ad3a1442-4036-11e5-8492-6337e0385e44.png)

**Comment by shanebp** [comment]
Trying to avoid crossed wires here...
afaik, this issue is also related to ( perhaps ongoing) javascript work ala issue 172

**Comment by shanebp** [comment]
On member activity pages, such as:
http://myfossil.staging.wpengine.com/members/shanebp/
This file is loaded:
`<script type='text/javascript' src='http://myfossil.staging.wpengine.com/wp-content/themes/myfossil/static/js/buddypress.min.js?ver=2.2.1'></script>`

But on the main activity page, aka front page, *buddypress.min.js* is not loaded

**Comment by woodb** [comment]
This appears to be fixed after updating to BuddyPress 2.4.0.

![image](https://cloud.githubusercontent.com/assets/1631487/9289555/e7eae5c6-4342-11e5-814a-f12dae45d9a5.png)

**Comment by shanebp** [comment]
No, it's still the same on the main activity page, aka front page
As noted, the issue seems to be that  buddypress.min.js is not loaded on that page.

**Comment by woodb** [comment]
Hey @shanebp, is it possible that in your `nginx.conf` on your Vagrant instance that `sendfile` is not commented out?

![image](https://cloud.githubusercontent.com/assets/1631487/9289648/d173d39a-4345-11e5-9370-297a64c82286.png)

**Comment by shanebp** [comment]
I'm only using staging.  
If you're not seeing it on your local install - that's a clue!

**Comment by woodb** [comment]
Yeah, I haven't yet pushed anything to staging...

**Comment by shanebp** [comment]
I'd love to find out that a push solved this.

The non-loading of buddypress.min.js on the landing page has confounded myself, eric and miko.  
Miko's attempts to solve it by specifically enqueueing that script caused the double posting issue #189

If a push doesn't solve it - we could try calling the activity loop on the landing page, instead of redirecting.

**Comment by woodb** [comment]
@shanebp can you get on Slack real quick?

**Comment by shanebp** [comment]
Brandon's push to staging did not solve this. 
The files on staging and B's local are the same.
Curses... 

I still think the issue is related to the non-loading of buddypress.min.js on the landing page.

On the landing page, the form element for each comment does NOT include an inline style.
On a personal activity page, the form element for each comment includes this: * style="display: none;"*
That tag is controlled by a call to *bp_activity_comment_form_nojs_display()* in this file:
myfossil-theme\buddypress\activity\entry.php

**Comment by woodb** [comment]
It's really oddball, I agree the problem is that `buddypress.min.js` is not being included. It *is* included on my local instance. It has to be an environment difference of some kind, because everything else is the same file and data wise... I even tried disabling plugins, etc. and no luck. 

The script enqueue is in `buddypress-functions.php`,

**Comment by shanebp** [comment]
I added `var_dump( $asset );` to `enqueue_scripts()` in `buddypress-functions.php`.
The result: `array(2) { ["location"]=> string(91) "http://myfossil.staging.wpengine.com/wp-content/themes/myfossil/static/js/buddypress.min.js" ["handle"]=> string(12) "bp-parent-js" }`
So buddypress.min.js is being found on the front page.

In `enqueue_scripts()` there is this comment `// NOTE: Disabled BP JS file in lieu of our own`
Is that comment true and what is 'our own' ?

**Comment by shanebp** [comment]
In  `enqueue_scripts()` in `buddypress-functions.php`, this will load the js on the front page, but doesn't solve the problem.
  `wp_enqueue_script($asset['handle'], $asset['location'], bp_core_get_js_dependencies(), false);`
( the difference is using `false` instead of `$this->version` )

**Comment by shanebp** [comment]
I changed `themes/myfossil/page-homepage.php` so that it calls the BP activity template, rather than redirecting to `/activity`. 
The original homepage is `page-homepage.php.BU`.

The comment forms are now collapsed by default.  
And ajax is working because the JS is loaded. 

if you add to existing comments, ajax will post it at the top of the comments for that activity post.  If you reload the page, it will appear at the bottom of those comments. And will appear 'standalone' at the top of the activity stream.  
*Which is also what happens on personal activity page.* 
So it's consistent. 

This is just on staging - nothing pushed to git. 

I'd still like to know what this comments means, in `enqueue_scripts()` in `buddypress-functions.php`
// NOTE: Disabled BP JS file in lieu of our own

**Comment by epoirier** [comment]
The workaround seems to be what we need for now.  Will reopen if it becomes an issue again.
