### ISSUE TITLE
Can't change category in Documents

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#247]
We are created a set of lesson plans in the documents section of the site.  We created a new category "Lesson Plans".  It seems we can't change the category.  Whenever we deselect "Misc", select "Lesson Plans", and update, the document continues to show "Misc" as the selected category.

For example, try to change the "PaleoTEACH" document to "Lesson Plans".

**Comment by shanebp** [comment]
Something has changed in the codebase since I wrote this plugin. 
On staging, you can now change the category. 
Note that a default category will no longer be selected. 
This is the file I tweaked:  `/wp-content/plugins/myfossil-documents/loader.php`

**Comment by epoirier** [comment]
Do you think this has to do with the update to WP 4.3?

**Comment by shanebp** [comment]
I don't see anything obvious in the changelogs for 4.3 or 4.3.1. 

But you were able to assign a Document to 'Report' in August
http://myfossil.staging.wpengine.com/wp-admin/post.php?post=1522&action=edit

And since then, this issue appeared. 

If you still want to auto-default all Documents to 'Misc' category, I can explore further.
